```yaml
version: '3'

services:
  bot:
    build: ./bot
    ports:
      - "4000:3000"  # Host:Container port
    restart: always

  admin:
    build: ./admin
    ports:
      - "4001:3000"
    restart: always
```

Run with:

```
docker-compose up -d
```
